# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02

    steps:
      - checkout
      - run:
          name: Build application Docker image
          command: |
           docker build . -t node_app
           docker run -p 8080:8080 -d node_app
           sleep 2
           curl -I localhost:8080 | grep "200 OK"

  publish:
    machine:
      image: ubuntu-2004:202107-02

    steps:
      - checkout
      - deploy:
          name: Deploy application Docker image
          command: |
           docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
           docker build . -t $DOCKER_LOGIN/node_app
           docker push $DOCKERHUB_LOGIN/node_app

workflows:
  executor:
    jobs:
      - build
      - publish:
          requires:
            - build