# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  build:
    docker:
      - image: docker/node-docker
        auth:
          username: manostri
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: Build application Docker image
          command: |
           docker build --tag node-docker .
           docker push node-docker

